name = "template-it"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-08-16"
compatibility_flags = ["nodejs_als"]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
not_found_handling = "single-page-application"

[observability]
enabled = true

[placement]
mode = "smart"
